# DONUT-hole model configuration
# DONUT model with adapter bottleneck and knowledge distillation

input_size: [2560, 1920]
align_long_axis: false
window_size: 10
encoder_layer: [2, 2, 14, 2]
decoder_layer: 4
max_length: 1536
name_or_path: "naver-clova-ix/donut-base"

# Adapter settings
use_adapter: true
adapter_bottleneck_dim: 256

# Distillation settings
teacher_model_path: "naver-clova-ix/donut-base"
distillation_temperature: 2.0
distillation_alpha: 0.7  # Higher weight on distillation loss

# Pruning settings
pruning_sparsity: 0.3  # 30% sparsity for prune-distill
pruning_method: "magnitude"